# This is going to be a guess game. The user will have 5 shots to guess the right number.
# The number will be randomly generated by the program through the "random" module

import random

print("Hello, please input your name: ")
name = input()  # Player username input
if name == '':  # Ending game prematurely if Name not provided
    print("You must insert a Name. The program will now close")
    print("Please re-open if you want to play again.")
    quit()  # Ending the game
print(f"Hello {name}, welcome to our Guess Game. You will have 4 shots to guess a number between 1 and 20.")

randomNumber = random.randint(1, 20)  # Random number generator

# Figuring out if input matches the random number generated
for guessesTaken in range(1, 5):
    # Converting the input value into an Integer and assigning it to a "guess" variable
    print(f"Guess nr. {guessesTaken}: ")
    try:  # Converting error to User-friendly message
        guess = int(input())
        if guess > randomNumber:  # Giving hints to help
            print("Your number is TOO HIGH. Try again")
        elif guess < randomNumber:
            print("Your number is TOO LOW. Try again")
        else:
            break  # Correct guess
    except (ValueError, NameError):
        print("Error: Please input a number between 1 and 20!")
# Checking if the input number was correct

try:
    if guess == randomNumber:
        # If guess was correct
        print(
            f"Congratulations, you won! The correct number was {randomNumber}")
    else:
        # If guess was wrong
        print()
        print(f"Sorry, you ran out of guesses. The number was: {randomNumber}")
except NameError:
    print("You haven't provided any valid information. The program will now close. Please re-open it if you want to play again!")
